project_name: "exportarr"
archives:
  - id: main
    wrap_in_directory: true
    files:
      - "README.md"
builds:
  - main: "./cmd/exportarr"
    binary: "exportarr"

    ldflags:
      - -s -w -X main.version={{.Version}} -X main.revision={{.Commit}} -X main.buildTime={{.CommitTimestamp}}

    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goos:
      - "darwin"
      - "linux"
      - "freebsd"
      - "openbsd"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64
    env:
      - CGO_ENABLED=0
