---
apiVersion: v1
kind: Service
metadata:
  name: &name prowlarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
  ports:
    - name: monitoring
      port: 9707