---
name: Binaries
description: Runs Go Releaser

inputs:
  token:
    description: Github token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies

    - name: Install Python Requirements
      shell: bash
      run: |
        pip install -r ./.github/scripts/requirements.txt && pip freeze

    - name: Update Files
      shell: bash
      run: |
        python3 ./.github/scripts/update_tags.py ${GITHUB_REF_NAME}
        git diff

    - name: Ensure only text files changed
      shell: bash
      run: |
        echo "Changed Files:"
        git diff --name-only
        if [ $(git diff --name-only | grep -vE 'examples/.*\.yaml$|.md$' | wc -l) != "0" ]
          then echo "Changing files other than example yaml files or markdown files is not allowed!"
          exit 1
        fi

    - name: Commit Changes
      shell: bash
      run: |
        git config --global user.name "bot-ross"
        git config --global user.email "98030736+bot-ross[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Image Tags in Documentation" || echo "No changes to commit"
        git push origin || echo "No changes to push"
