---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: &name bazarr-exporter
    app.kubernetes.io/instance: *name
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
      app.kubernetes.io/instance: *name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
        app.kubernetes.io/instance: *name
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: bazarr-exporter
          image: ghcr.io/onedr0p/exportarr:v1
          imagePullPolicy: IfNotPresent
          args:
            - bazarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://bazarr.default.svc.cluster.local:6767"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: bazarr-exporter
                  key: api-key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
