---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &name sabnzbd-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
      app.kubernetes.io/instance: *name
  endpoints:
    - port: monitoring
      interval: 4m
      scrapeTimeout: 90s
      path: /metrics