---
name: Tests
description: Runs Go tests

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.23"

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2
        args: --timeout=5m --config=.github/lint/golangci.yaml
