---
name: Tests
description: Runs Go tests

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ">=1.25"

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.4
        args: --timeout=5m --config=.github/lint/golangci.yaml
