---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml

commonLabels:
  app.kubernetes.io/part-of: exportarr
  k8s-app: exportarr